name: lovestory
description: "lovestory"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  firebase_core:
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  timezone: ^0.10.0
  flutter_dotenv: ^5.2.1
  google_mobile_ads: ^5.2.0
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
 
  assets:
    - assets/you.gif
    - assets/splash_animation.json
    - assets/love.json
    - assets/mail.json
    - assets/push_mail.json  
    - assets/send_mail.json
    - assets/heart_map_icon.png
    - assets/config/.env
    - assets/home_image.png
    - assets/man_profile_image.png
    - assets/woman_profile_image.png
    
  fonts:
    - family: prettendardBlack
      fonts:
       - asset: assets/fonts/Pretendard-Black.otf
    - family: prettendardExtraBold    
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
    - family: prettendardThin
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
    - family: ImperialScript-Regular
      fonts:   
        - asset: assets/fonts/ImperialScript-Regular.ttf
    - family: GowunDodum-Regular
      fonts:
        - asset: assets/fonts/GowunDodum-Regular.ttf
    - family: CuteFont
      fonts:
        - asset: assets/fonts/CuteFont-Regular.ttf
  uses-material-design: true
